# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  required_providers {
    azapi = {
      source  = "azure/azapi"
      version = "~>1.14.0"
    }
  }
  backend "local" {
  }
}
provider "azurerm" {
  features {

  }
  subscription_id = var.subscription_id
}
