#escape = `
ARG TAG=lts-nanoserver-1809
FROM mcr.microsoft.com/powershell:$TAG
SHELL ["pwsh", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]
USER ContainerAdministrator
WORKDIR c:\prep
RUN Invoke-WebRequest "https://github.com/PowerShell/Win32-OpenSSH/releases/download/V8.6.0.0p1-Beta/OpenSSH-Win64.zip" -OutFile OpenSSH-Win64.zip -UseBasicParsing; `
   Expand-Archive OpenSSH-Win64.zip .; Remove-Item OpenSSH-Win64.zip`
   & .\OpenSSH-Win64\install-sshd.ps1; `
   Set-Service sshd -StartupType Manual; Set-Service ssh-agent -StartupType Manual; `
   sc.exe failure sshd reset= 86400 actions= restart/500 
ENTRYPOINT if ($env:bootstrapLocation) {Invoke-Expression (Invoke-WebRequest $env:bootstrapLocation).Content } ;`
   foreach ($user in (Get-Content $env:configLocation\users.json | convertfrom-JSON).users) { `
   net user /add $user.username $user.password ; `
   (Test-Path "$env:sftpLocation\$($user.username)") ? (Write-Output "Folder $($user.username) already exists"):(New-Item -ItemType Directory -path "$env:sftpLocation\$($user.username)"); `
   };`
   New-item c:\programdata\ssh\ -ItemType Directory -ErrorActionPreference Ignore; Copy-Item -Path $env:configLocation\* -Destination c:\programdata\ssh\ ;  & .\OpenSSH-Win64\FixHostFilePermissions.ps1 -Confirm:$false; & .\OpenSSH-Win64\FixUserFilePermissions.ps1 -Confirm:$false;`
   Start-Service sshd; (Test-path C:\ProgramData\ssh\logs\sshd.log)? (Write-Output 'Log Folder already exists'): (new-item "C:\ProgramData\ssh\logs\sshd.log");`
   while ($true) {get-content C:\ProgramData\ssh\logs\sshd.log -tail 1 -wait} 
