apiVersion: v1
kind: Namespace
metadata:
  name: "sftp"
---
apiVersion: v1
kind: Secret
metadata:
  name: sftp-secret
  namespace: sftp
type: Opaque
stringData:
  users.json: |
    {
      "users": [
          {
            "username": "greg",
            "password": "123"
          },
          {
            "username": "socrates",
            "password": "1234"
          }
      ]
    }
  sshd_config: |
    # This is the sshd server system-wide configuration file.  See
    # sshd_config(5) for more information.

    # The strategy used for options in the default sshd_config shipped with
    # OpenSSH is to specify options with their default value where
    # possible, but leave them commented.  Uncommented options override the
    # default value.

    #Port 22
    #AddressFamily any
    #ListenAddress 0.0.0.0
    #ListenAddress ::

    #HostKey __PROGRAMDATA__/ssh/ssh_host_rsa_key
    #HostKey __PROGRAMDATA__/ssh/ssh_host_dsa_key
    #HostKey __PROGRAMDATA__/ssh/ssh_host_ecdsa_key
    #HostKey __PROGRAMDATA__/ssh/ssh_host_ed25519_key

    # Ciphers and keying
    #RekeyLimit default none

    # Logging
    SyslogFacility LOCAL0
    LogLevel DEBUG3

    # Authentication:

    #LoginGraceTime 2m
    #PermitRootLogin prohibit-password
    #StrictModes yes
    #MaxAuthTries 6
    #MaxSessions 10

    #PubkeyAuthentication yes

    # The default is to check both .ssh/authorized_keys and .ssh/authorized_keys2
    # but this is overridden so installations will only check .ssh/authorized_keys
    AuthorizedKeysFile	.ssh/authorized_keys

    #AuthorizedPrincipalsFile none

    # For this to work you will also need host keys in %programData%/ssh/ssh_known_hosts
    #HostbasedAuthentication no
    # Change to yes if you don't trust ~/.ssh/known_hosts for
    # HostbasedAuthentication
    #IgnoreUserKnownHosts no
    # Don't read the user's ~/.rhosts and ~/.shosts files
    #IgnoreRhosts yes

    # To disable tunneled clear text passwords, change to no here!
    #PasswordAuthentication yes
    #PermitEmptyPasswords no

    # GSSAPI options
    #GSSAPIAuthentication no

    #AllowAgentForwarding yes
    #AllowTcpForwarding yes
    #GatewayPorts no
    #PermitTTY yes
    #PrintMotd yes
    #PrintLastLog yes
    #TCPKeepAlive yes
    #UseLogin no
    #PermitUserEnvironment no
    #ClientAliveInterval 0
    #ClientAliveCountMax 3
    #UseDNS no
    #PidFile /var/run/sshd.pid
    #MaxStartups 10:30:100
    #PermitTunnel no
    ChrootDirectory c:\sftp\
    #VersionAddendum none

    # no default banner path
    #Banner none

    # override default of no subsystems
    Subsystem	sftp	sftp-server.exe  -f LOCAL0 -l DEBUG3 -d "c:\sftp\"

    # Example of overriding settings on a per-user basis
    #Match User anoncvs
    #	AllowTcpForwarding no
    #	PermitTTY no
      ForceCommand internal-sftp

    Match User *
    ChrootDirectory c:\sftp\%u

    Match Group administrators
          AuthorizedKeysFile __PROGRAMDATA__/ssh/administrators_authorized_keys
  ssh_host_ed25519_key: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
    QyNTUxOQAAACBkqePL1p4dFDk3DQOxu4zlyGa+eTZssX9uCgJCve1DUgAAALC+1suHvtbL
    hwAAAAtzc2gtZWQyNTUxOQAAACBkqePL1p4dFDk3DQOxu4zlyGa+eTZssX9uCgJCve1DUg
    AAAECEVjFuAEZXqvb9AenBvAknXZn7QUmgEHDlIFOJVu73D2Sp48vWnh0UOTcNA7G7jOXI
    Zr55Nmyxf24KAkK97UNSAAAAK3N5c3RlbUA3MDMzYTgxNC1hZTg3LTRkMjAtYmU0My05ZW
    NjYjM2MTE0ZTIBAg==
    -----END OPENSSH PRIVATE KEY-----
  ssh_host_rsa_key: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABlwAAAAdzc2gtcn
    NhAAAAAwEAAQAAAYEA4VqEuhD47ypOUWZMsCqYsyOQviOYWRfqIHtyORhACIs+tiRW4xGd
    /BIIMNMTKJjO9bqlulucBcepZ5Fozluyk++UYEUKVK4ONP5dCR9lh5XDZzzeHhWiYDR4oG
    HheCV7Py3MnjlHVY3IX4qbYopQE28IGeWpMQR4wK1bvztKgwW56Zcd2i/x5InK4/pMLqtX
    itEQTazS325TEegOwxsFTPNW6Yb/HPs2MCwzY2wXX7zx0cQ28It4+WY344RBeK8BVRKQUO
    ppTbscfNgiCIb7WOne8p8qTOxH+zPXzGvOA3Jr8mQTT/kbqNfChysM4BAcANMt9muXoW4F
    we4wTH8Wyev2F5n68DFADMw+C9/SRdq15lyl2FCrdGQzJbi7J9mCc8HnqdDy/yNJpRmhtl
    gld2qqWL8q/eGtZ/85tBKiRxcI3xz+Z/BrZrpL9i1+XaTzeArcA7wp5IUkxi3K9K2gE3hD
    UXRsRAJysl5LYouXRrv7dnIM2n6LOzGo+LZYeLlDAAAFoMt1u6/LdbuvAAAAB3NzaC1yc2
    EAAAGBAOFahLoQ+O8qTlFmTLAqmLMjkL4jmFkX6iB7cjkYQAiLPrYkVuMRnfwSCDDTEyiY
    zvW6pbpbnAXHqWeRaM5bspPvlGBFClSuDjT+XQkfZYeVw2c83h4VomA0eKBh4Xglez8tzJ
    45R1WNyF+Km2KKUBNvCBnlqTEEeMCtW787SoMFuemXHdov8eSJyuP6TC6rV4rREE2s0t9u
    UxHoDsMbBUzzVumG/xz7NjAsM2NsF1+88dHENvCLePlmN+OEQXivAVUSkFDqaU27HHzYIg
    iG+1jp3vKfKkzsR/sz18xrzgNya/JkE0/5G6jXwocrDOAQHADTLfZrl6FuBcHuMEx/Fsnr
    9heZ+vAxQAzMPgvf0kXateZcpdhQq3RkMyW4uyfZgnPB56nQ8v8jSaUZobZYJXdqqli/Kv
    3hrWf/ObQSokcXCN8c/mfwa2a6S/Ytfl2k83gK3AO8KeSFJMYtyvStoBN4Q1F0bEQCcrJe
    S2KLl0a7+3ZyDNp+izsxqPi2WHi5QwAAAAMBAAEAAAGAN1HZMzPnaA6imyjZuoU6Zv9cEN
    D8HSLZvo+PQqTJU0+bXWseSS+R8Mcca5/lHBom8/uVo2HJs0GIPHxdlgq8k8REUD2ig5cW
    tbubaxnh+p6xES7H9+qnqaY31mcwyiWpU6ESkeTNthrQDWQhMNdzQNII0xKlrfrDCcmEtD
    UB3ZgSQ11tXppWbxvESqKvAOXe35ziu66pNWAH1GV6+jov2uwBceJJzft9GeY/1zA5rK7d
    Tfk042fZkp+dKKTWzaFn5GUmqFmgPPkeqG+TegXKefcJNJNVWxkb7WEhXVAB8+MBEJcaG2
    +IijXaT5RbbMTfniCDV8pejTqetnDMLKDsViHBAI6fKWNkE9Qb/HpOYY61zlh8ndThqvGC
    oaSs2LBxueLh3OTv2c/tKY62qLSLq39A/XBy9FbDLRlXYDzdF5qXcJXvZryDMChLKGXMHm
    xHTJj+cNZy62wr6fwjT8aXHx8J4adMNMDHLomXIPJ2S0+nk2r8nNTAL5GOHki9M/XBAAAA
    wFGeubyg9gP9A+vaY0Pryib7sXVVAbU7DTL6nvjnfvNJFwjgGoLaFU5UiCdcfbGYDzuoyA
    x1Zup0fQ0FJ7xqR3tgGSzj3PBO7O4MbS9lumKYtVEHbW7SGNrjuGb293cJJDwgNyAOxauQ
    KZG9D377N98+OJHLSfX1BlDOp8mm8RK94m/afpnH19fz00FZfJktyhM4SfAoX1ykxQkbYe
    2ZJ6qR4Q5nYEv5wAHzt7I3syKNIeQWINH+VCdKMJrQLPX9tgAAAMEA8aEQ/I0yehKpPFNd
    fXft6mxiaslzHAd1dvenu0DHrIiL1JLgFu9BsjcIt2mwNNuikI0XjdGyqD4v9xRvj93a+E
    HkD3O0Lq0rBrH+BvVD3qguay6Muk77wSY4AUlSeAvTdyjmC0ujYre92Tx9gSw+4Ya6Caek
    Se76AYJg5vOgZbLZGLcjF4wCbOXCHgVnzGEjORngBfBagT+efsDs0E81cZuyjzWlTV3o4g
    Kuk4VNG/yeEOQ9TULE1bmr6afYka4PAAAAwQDuwaXQWYNbNfMp4yl3bzg1Tvi3wTCIX44N
    o3KrbwO7RjdjEM6dlEpXZruB3ndBqyziNH8r6l/S+m8LZkAT4Fvp4bbZLo4rxUzLKOR7NH
    jT9S5Kc46DsgEsw010hJCS0nuFPpBTbtSoxZA6bPygbyw3xO72Fh6fbOqWR9Glt89FdD3a
    zsCBuOgS+u4lSPyojfAvJsipEF1stMuPOLfDNXGK+hVEU7A9V5YsQY2eoBR7XGgrFSFH9e
    9RdHX/CPhhdY0AAAArc3lzdGVtQDcwMzNhODE0LWFlODctNGQyMC1iZTQzLTllY2NiMzYx
    MTRlMg==
    -----END OPENSSH PRIVATE KEY-----

---
apiVersion: v1
data:
  azurestorageaccountkey: N3g1eUtYMFpnVCtNoNHpMUGFtZnFZMEFYS2FsN3lSVjVoNUJrTWJWaVVHeklHb2RXcDJLSkMzblVOK3BWb3NJM0lmam9DWTBFSlppN3ZERk45Umc9PQ==
  azurestorageaccountname: Y29yZTM2MHN0b32VzaGFyZQ==
kind: Secret
metadata:
  name: fileshare-secret
  namespace: sftp
type: Opaque
