version: "3.9"
services:
  miner:
    build: .
    image: artisticcheese/miner:11
    command:
      - sh
      - ./ETH-2miners.sh
    ports:
      - 4067:4067
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
