version: "3.9"
services:
  miner:
    build: .
    image: artisticcheese/miner:etc-2miners
    command:
      - sh
      - ./ETC-2miners.sh
    ports:
      - 4067:4067
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
