version: "3.9"
services:
  miner:
    build: .
    image: artisticcheese/miner:11.7.1
    command:
      - sh
      - ./ETC-2miners.sh
    ports:
      - 80:80
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
