apiVersion: apps/v1
kind: Deployment
metadata:
  name: aks-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aks
  template:
    metadata:
      labels:
        app: aks
    spec:
      containers:
        - name: aks
          image: artisticcheese/aks-servercore
          volumeMounts:
            - name: logs
              mountPath: "logs"
            - name: logs
              mountPath: "logs1"
            - name: logs
              mountPath: "logs2"
            - name: logs
              mountPath: "logs3"
            - name: logs
              mountPath: "logs4"
            - name: logs
              mountPath: "logs5"
        - name: aks-clean
          image: artisticcheese/aks-servercore
      nodeSelector:
        kubernetes.io/os: windows
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: agentpool
                    operator: In
                    values:
                      - mspool
      tolerations:
        - key: kubernetes.io/os
          operator: Equal
          value: windows
          effect: NoSchedule
      volumes:
        - name: logs
          azureFile:
            secretName: fileshare-secret
            shareName: logs
            readOnly: false
