#escape = ` 
FROM mcr.microsoft.com/powershell:7.2.1-nanoserver-1809
SHELL ["pwsh", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'Continue'; $verbosePreference='SilentlyContinue';"]
USER ContainerAdministrator
RUN   find-module SQLServer | install-module -force -SkipPublisherCheck -scope AllUsers